name: Gatsby Publish

on:
  push:
    branches:
      - dev

env:
  SANITY_PROJECT_ID: ${{ env.SANITY_PROJECT_ID }}
  SANITY_DATASET: ${{ env.SANITY_DATASET }}
  SANITY_READ_TOKEN: ${{ env.SANITY_READ_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          working-dir: ./web