name: Gatsby Publish

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          working-dir: ./web
        env: 
          SANITY_PROJECT_ID: ${{ env.jezpoz-github-page.SANITY_DATASET }}
          SANITY_DATASET: ${{ env.jezpoz-github-page.SANITY_DATASET }}
          SANITY_READ_TOKEN: ${{ env.jezpoz-github-page.SANITY_READ_TOKEN }}